parm = [];
parm.atm.photometry             = photometry.V0;                % photometric band
parm.atm.windSpeed              = [6.8 6.9 7.1 7.5 10.0 26.9 18.5];                           % wind speed vector in m/s
parm.atm.windDirection          = [0 pi/2 pi/4 3*pi/2 -pi/4 pi/6 -pi/4];                            % wind direction vector in rad
parm.atm.r0                     = 0.16;                         % coherence lenght in meters at 0.5microns
parm.atm.L0                     = 25;                           % Outer scale in meters
parm.atm.altitude               = [0 .5 1 2 4 8 16]*1e3;                            % altitude vector in meters
parm.atm.fractionalR0           = [0.517 0.119 0.063 0.061 0.105 0.081 0.054];                            % fractional Cn2 profile (sum=1)                                              
parm.sci.photometry             = photometry.H;                % photometric band
parm.sci.x                      = 0;                            % Sources x cartesian position in arcsec
parm.sci.y                      = 0;                            % Sources x cartesian position in arcsec
parm.tel.D                      = 11.25;                            % telescope primary mirror diameter
parm.tel.obstructionRatio       = 0.2356;                         % central obscuration ratio
parm.nGs.photometry             = photometry.R;                % photometric band                    
parm.nGs.x                      = [0];                          % NGSs x cartesian position in arcsec
parm.nGs.y                      = [0];                          % NGSs y cartesian position in arcsec                   
parm.dm.pitch                   = 0.5625;                          % dm pitch
parm.dm.nActuators                   = 21;                         
parm.cam.pixelScale             = 9.94;                          % Pixel scale in mas                         
parm.cam.resolution             = 168;                          % Detector resolution
parm.cam.ron                    = 38;